# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

enumerate_simplex_cpp <- function(p, n, count) {
    .Call(`_simplexity_enumerate_simplex_cpp`, p, n, count)
}

